### ISSUE TITLE
no limit to dashboard events

### ISSUE THREAD

**Issue by kyle-richardson** [Lambda-School-Labs/neighborhood-chef-fe#117]
there is no limit to events shown on dashboard, causing extreme delays while fetching large amounts of data, that is mostly useless to the user.

Unsure what limit should be, but there should be one.

**Comment by PaulMEdwards** [comment]
Recommend making the limit an environment variable so it can be tweaked without touching code.

**Comment by PaulMEdwards** [comment]
Should it always show the current user's events irrespective of the limit?

**Comment by kyle-richardson** [comment]
in thinking about how the dashboard view is meant to be used, it seems a user would want to see newest events created by neighbors since he/she last logged in.  treating it like social media approach would dictate that user would not necessary even need to see their own evens in the dashboard at all, as we would have their specifically created events easily accessible from the account button at top right.

In an effort to be as simplistic in fixing this issue as possible, though, I don't think we should change rules based on who created, but rather set a hard limit to items shown using environment variable.
