### ISSUE TITLE
Font size on Dashboard event entry main text is a bit too small

### ISSUE THREAD

**Issue by PaulMEdwards** [Lambda-School-Labs/neighborhood-chef-fe#29]
The font size of the items encircled in red on the screenshot below are too small.

![2020-05-15](https://user-images.githubusercontent.com/153847/82107901-e9a50180-96df-11ea-91c3-06c5a4514230.png)

**Comment by kyle-richardson** [comment]
should be better scaled per PR #32, changed theme for typography on cards, which included the red circled sections you listed as well as other font sizes to attempt to match other pages in the app.

**Comment by PaulMEdwards** [comment]
The Going / Maybe Going / Not Going text below the time on the card should be bigger and spaced a little further down from the time, @kyle-richardson.

**Comment by kyle-richardson** [comment]
updated in PR 39
