### ISSUE TITLE
Controls not yet functional and not part of 1st Release should be hidden

### ISSUE THREAD

**Issue by PaulMEdwards** [Lambda-School-Labs/neighborhood-chef-fe#30]
These controls are not currently working and should not be visible as part of our 1st release MVP:

- Edit Neighborhood Name
- Search
- Recent Messages cards group
- Cards
  - 3 dot overflow menu
  - Heart (like/favorite) icon
  - Comment icon

**Comment by kyle-richardson** [comment]
this is potentially resolved in PR #32, completely removed buttons for now
