### ISSUE TITLE
RSVP down arrow should rotate 180 degrees to point up when RSVP controls shown

### ISSUE THREAD

**Issue by PaulMEdwards** [Lambda-School-Labs/neighborhood-chef-fe#31]
And it should rotate back when hidden.

**Comment by kyle-richardson** [comment]
this is potentially resolved in PR #32.  however, RSVP letters were removed.  Could be added back potentially with some work, since we are utilizing material UI components for most of the elements in each card, and it doesn't play nice removing RSVP from the button.
